version: "3.9"

services:
  database: 
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres


  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app
    links: 
      - backend
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
